{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backend-stack.componentName" (dict "root" . "component" "migrations") }}
  labels:
    {{- include "backend-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": {{ .Values.migrations.hookDeletePolicy | quote }}
spec:
  activeDeadlineSeconds: {{ .Values.migrations.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  {{- with .Values.migrations.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "backend-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrations
      {{- with .Values.migrations.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ default "default" .Values.migrations.serviceAccount.name }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.migrations.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrations
          image: "{{ .Values.migrations.image.repository }}:{{ default .Values.global.defaultImageTag .Values.migrations.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          {{- with .Values.migrations.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            {{- toYaml .Values.migrations.command | nindent 12 }}
          {{- with .Values.migrations.env }}
          env:
            {{- range $envName, $envValue := . }}
            - name: {{ $envName }}
              value: {{ $envValue | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.migrations.envFromSecrets }}
          envFrom:
            {{- range . }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
          {{- with .Values.migrations.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
