global:
  awsRegion: eu-central-1
  defaultImageTag: sha-localstack

workloads:
  api:
    replicaCount: 0
    autoscaling:
      enabled: false
    image:
      repository: 000000000000.dkr.ecr.eu-central-1.localhost.localstack.cloud:4566/pytorch-model/api
      tag: sha-localstack
    env:
      APP_ENVIRONMENT: production
      APP_HTTP_PROTOCOL: http
      APP_LOG_LEVEL: INFO
      APP_DOMAIN: localhost.localstack.cloud
      CORS_ALLOWED_ORIGINS: http://localhost:4321,http://localhost:5173
      MODEL_SERVICE_URL: http://pytorch-model-backend-stack-model-runtime-host:8001
      S3_UPLOAD_MODE: aws
      AWS_REGION: eu-central-1
      S3_BUCKET_NAME: pytorch-model-local-artifacts
    envFromSecrets: []
    ingress:
      enabled: false
    externalSecret:
      enabled: false

  model-runtime-host:
    enabled: false

migrations:
  enabled: false

modelRuntimes: {}
